version: "3.8"
services:

    # PHP Service
    php:
        build:
            context: .
            target: php
        environment:
            APP_ENV: ${APP_ENV}
            CONTAINER_ROLE: app
            DB_HOST: database
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - database
            - redis

    # Database Service
    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    # Redis Service
    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        ports:
            - 6379:6379

    # Node Service
    node:
        build:
            context: .
            target: node
        environment:
            NODE_ENV: development
        working_dir: /var/www
        volumes:
            - .:/var/www
        tty: true

volumes:
    db-data:
